### PR TITLE
Document how to create a slideshow in the README

### PR DESCRIPTION
**Pull request by kir0ul**
Fix issues https://github.com/jupyterlab-contrib/rise/issues/73 and https://github.com/jupyterlab-contrib/rise/issues/45.

### CODE REVIEW

**Review by fcollonval — CHANGES_REQUESTED** [review]
Thanks @kir0ul but could you please rather add the images within the repository instead of linking external images (especially as they involved authentication and token...).

**Comment by kir0ul** [comment]
> Thanks @kir0ul but could you please rather add the images within the repository instead of linking external images (especially as they involved authentication and token...).

Sure, I just didn't know where to put them. What's the best place where those images could go?

**Comment by fcollonval** [comment]
@kir0ul could you create a `docs` folder in the repo to store them?

**Comment by kir0ul** [comment]
> @kir0ul could you create a `docs` folder in the repo to store them?

@fcollonval Done :heavy_check_mark:

**Review by fcollonval — APPROVED** [review]

**Comment by fcollonval** [comment]
Thanks @kir0ul

**Pull request merged**
